- name: Regist solr source folder
  stat: path=/opt/{{ solr_filename }}
  sudo: yes
  register: solr_source_folder

- name: Create sources directory
  sudo: yes
  file: >
    path=/opt
    state=directory
  when: not solr_source_folder.stat.exists

- name: Download Solr
  sudo: yes
  get_url: 
    url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz
    dest=/opt/{{ solr_filename }}.tgz
    force=no
  when: not solr_source_folder.stat.exists

- name: Extract Solr
  sudo: yes
  command: 
    tar -C /opt -xvzf /opt/{{ solr_filename }}.tgz
    creates=/opt/{{ solr_filename }}
  when: not solr_source_folder.stat.exists

- name: Execute install_solr_service.sh
  sudo: yes
  shell: /opt/{{ solr_filename }}/bin/install_solr_service.sh /opt/{{ solr_filename }}.tgz
  when: not solr_source_folder.stat.exists

- name: Add symlink solr to bin folder
  sudo: yes
  file: src=/opt/solr/bin/solr dest=/usr/bin/solr state=link
