# This is solrserver playbook
#
#

- hosts: solarservers
  remote_user: vagrant
  vars:
      solr_version: 6.0.0
      solr_filename: solr-6.0.0 
  roles:
    - common
    - role: ansibl3.ubuntu_sunjava
    - apache-solr
