# This is solrserver playbook
# 
# [requirements]
# - setting for loggin with no password (.ssh/config)
#

- hosts: solarservers
  remote_user: vagrant
  vars:
      solr_version: 6.0.0
      solr_filename: solr-6.0.0 
  roles:
    - common
    - role: ansibl3.ubuntu_sunjava
    - apache-solr
