# This is solrserver playbook
#
#
#
#

- hosts: solarservers
  vars:
      solr_version: 6.0.0
      solr_version: 6.0.0
      solr_filename: solr-6.0.0 
  tasks:
    - apt: update_cache=yes
      sudo: yes
  roles:
      - { role: ansibl3.ubuntu_sunjava }
      - common
      - apache-solr
